export const FIND_ALL_CHARACTERS_START = 'FIND_ALL_CHARACTERS_START'
export const FIND_ALL_CHARACTERS_END = 'FIND_ALL_CHARACTERS_END'

export const FIND_ONE_CHARACTER_START = 'FIND_ONE_CHARACTER_START'
export const FIND_ONE_CHARACTER_END = 'FIND_ONE_CHARACTER_END'

export const FIND_CHARACTERS_BY = 'FIND_CHARACTERS_BY'

export const RESET_STATE = 'RESET_STATE'